api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Domain/Entity']
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
        html: [ 'text/html' ]
    patch_formats:
        json: ['application/json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
