doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8
        default_table_options:
            charset: utf8
            collate: utf8_general_ci
        schema_filter: ~^(?!(b_ipol_dpd_|wf_|wrf_|migration_versions|
            |deal|foreign_currency|notifications|
            |mystore_c|mystore_g|mystore_r|mystore_u|mystore_s|
            |notifications|users_notifications_check|social_linking|
            |mystore_import_logs|mystore_import_matching_fields|mystore_import_settings|
            |refresh_tokens|
            ))~

        mapping_types:
            enum: string

        types:
            EnumOrderEventsType: App\Doctrine\DBAL\EnumOrderEventsType
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Domain/Entity'
                prefix: 'App\Domain\Entity'
                alias: App

        dql:
            string_functions:
                field: DoctrineExtensions\Query\Mysql\Field
