nelmio_cors:
    defaults:
#        origin_regex: true
#        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
        expose_headers: ['Link', 'X-PAGINATION-TOTAL', 'X-PAGINATION-PER_PAGE', 'X-PAGINATION-TOTAL_PAGES', 'X-PAGINATION-CURRENT_PAGE']
        max_age: 360000
#    paths:
#        '^/api/':
#            allow_origin: [ '*' ]
#            allow_headers: [ '*' ]
#            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#            max_age: 360000
#        '^/':
#            allow_origin: [ '*' ]
#            allow_headers: [ '*' ]
#            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#            max_age: 360000