# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    acme_api.event.authentication_success_listener:
        class: App\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }
    acme_api.event.jwt_decoded_listener:
        class: App\EventListener\JWTDecodedListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_decoded, method: onJWTDecoded }
    App\Security\SecurityInterface:
        class: App\Security\UserSecurity
    App\Service\Order\OrderNumberGenerator\OrderNumberGeneratorInterface:
        class: App\Service\Order\OrderNumberGenerator\OrderNumberGeneratorBySupplier

    App\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]
#    App\OpenApi\RefreshTokenDecorator:
#        decorates: 'api_platform.openapi.factory'
#        arguments: [ '@.inner' ]
#    App\OpenApi\RegistrationDecorator:
#        decorates: 'api_platform.openapi.factory'
#        arguments: [ '@.inner' ]
#    App\OpenApi\api2\CheckDecorator:
#        decorates: 'api_platform.openapi.factory'
#        arguments: [ '@.inner' ]
#
#    App\EventListener\ExceptionListener:
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception }
    App\EventSubscriber\UserEventSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventSubscriber\TagEventSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventSubscriber\ProductEventSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventSubscriber\CategoryEventSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventSubscriber\ShowcaseEventSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventSubscriber\CompanyEventSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventSubscriber\OrderEventSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventSubscriber\OrderProductEventSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App\EventSubscriber\OrderDataEventSubscriber:
        public: true
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        # Uncomment only if autoconfiguration is disabled
        #tags: [ 'api_platform.data_transformer' ]

    # App\EventSubscriber\ProductPackageEventSubscriber:
    #     public: true
    #     tags:
    #         - { name: doctrine.event_subscriber, connection: default }

#    Doctrine\Migrations\Version\MigrationFactory: App\Migrations\Factory\MigrationFactoryDecorator
    # Doctrine\Migrations\Version\DbalMigrationFactory: ~
    # App\Migrations\Factory\MigrationFactoryDecorator:
    #     decorates: Doctrine\Migrations\Version\DbalMigrationFactory
    #     arguments: [ '@App\Migrations\Factory\MigrationFactoryDecorator.inner', '@service_container' ]

    App\DataTransformer\Order\OrderActionDataTransformer: ~
            
    App\DataTransformer\Employee\EmployeeCreateDtoDataTransformer: ~
    App\DataTransformer\Employee\EmployeeEditDtoDataTransformer: ~

    App\DataTransformer\User\UserPermissionTemplateInputDataTransformer: ~
    App\DataTransformer\User\UserPermissionTemplateEditDataTransformer: ~

    App\DataTransformer\User\UserPermissionTemplateOutputDataTransformer: ~

    App\DataTransformer\User\UserUpdateDataTransformer: ~
